from typing import Protocol, Optional, runtime_checkable


class IOutputHandler(Protocol):
    def display(self, text: str) -> None: ...


class ICash(Protocol):
    def add_cash(self, amount: float) -> None: ...
    def reduce_cash(self, amount: float) -> None: ...
    def get_balance(self) -> float: ...


@runtime_checkable
class IItem(Protocol):
    def get_name(self) -> str: ...
    def is_stackable(self) -> bool: ...
    def get_max_stack(self) -> int: ...
    def get_cost_price(self) -> float: ...
    def get_selling_price(self) -> float: ...
    def get_description(self) -> str: ...


@runtime_checkable
class IWeapon(IItem, Protocol):
    def get_attack_points(self) -> int: ...


@runtime_checkable
class IHealingItem(IItem, Protocol):
    def get_health_points(self) -> int: ...


class IInventoryStorage(Protocol):
    """Low-level slot operations"""

    def add_item(self, item: IItem, quantity: int = 1) -> None: ...
    def get_unadded_items(self, item: IItem, quantity: int = 1) -> int: ...
    def try_add_item(self, item: IItem, quantity: int = 1) -> int: ...
    def find_item(self, item_name: str) -> Optional[IItem]: ...
    def is_full(self) -> bool: ...
    def list_items(self) -> list[tuple[int, IItem, int]]: ...
    def get_items_with_quantity(self) -> list[tuple[IItem], int]: ...
    def count_item(self, item_name: str) -> int: ...
    def remove_item(
        self,
        index: Optional[int] = None,
        item_name: Optional[str] = None,
        quantity: int = 1,
    ) -> tuple[Optional[IItem], int]: ...

    # def remove_item(self, item_name: str) -> Optional[IItem]: ...
    # def remove_item_by_index(self, index: int) -> Optional[IItem]: ...
    # def get_slot_by_name(self, item_name: str) -> Optional["Slot"]: ...


class IInventoryManager(Protocol):
    """User-facing inventory operations"""

    def view_description(self, item_name: str) -> str: ...
    def get_weapon(self, weapon_name: str) -> Optional[IWeapon]: ...
    def get_healing_item(self, healing_item_name: str) -> Optional[IHealingItem]: ...
    def get_unique_items(self) -> list[IItem]: ...

    # def discard_item(
    #     self, index: Optional[int] = None, item_name: Optional[str] = None
    # ) -> Optional[IItem]: ...
    # def discard_item_by_name(self, item_name: str) -> str: ...
    # def discard_item_by_index(self, index: int) -> str: ...
    # def get_inventory_items(self) -> list[str]: ...


class IInventory(Protocol):
    """Facade combinig storage + manager"""

    @property
    def storage(self) -> IInventoryStorage: ...
    @property
    def manager(self) -> IInventoryManager: ...


# All these methods are defined in IInventoryStorage and IInventoryManager
# def add_item(self, item, quantity: int = 1) -> int: ...
# def get_weapon(self, weapon_name: str) -> IWeapon | None: ...
# def get_healing_item(self, healing_item_name: str) -> IHealingItem | None: ...
# def get_slot_by_name(self, item_name: str): ...
# def is_full(self) -> bool: ...
# def discard_item_by_name(self, item_name) -> None: ...


class IPlayer(Protocol):
    """Player specific interface composed of cash + inventory"""

    @property
    def name(self) -> str: ...
    @property
    def max_health_points(self) -> int: ...

    # def get_cash(self) -> float: ...
    def get_equipped_weapon(self) -> Optional[IWeapon]: ...
    def get_health_points(self) -> int: ...
    def update_health_points(self, amount: int) -> None: ...

    @property
    def inventory(self) -> IInventory: ...
    @property
    def cash(self) -> ICash: ...

    # def get_cash(self) -> float: ...
    # def add_cash(self) -> None: ...
    # def reduce_cash(self) -> None: ...
    # def get_unique_items(self) -> list[str]: ...
